### ISSUE TITLE
Can't see Server in LAN browser

### ISSUE THREAD

**Issue by ppaulis** [PhasecoreX/docker-ut2004-server#18]
Hi!

first of all, thanks for the great work and keeping those games alive! :-) 

I'm running your image in a docker-compose setup for my upcoming LAN Party :
```
version: "3.7"

volumes:
  ut2004:
    name: ut2004

services:
  ut2004:
    image: phasecorex/ut2004-server
    container_name: ut2004
    ports:
      - 10.0.0.11:7777:7777/udp
      - 10.0.0.11:7778:7778/udp
      - 10.0.0.11:7787:7787/udp
    environment:
      CD_KEY: xxxxx-xxxxx-xxxxx-xxxxx
      PUID: 1000
    volumes:
      - type: volume
        source: ut2004
        target: /data
```

I changed the master server to openspy. But I can't see the server in UT2004's LAN browser.

Output of the container is :
```
Starting with UID/GID: 1000/1000
Starting server...
Executing Class Engine.ServerCommandlet
Browse: DM-Antalus?Name=Player?Class=Engine.Pawn?Character=Jakob?team=255?game=xGame.xDeathMatch
Collecting garbage
Purging garbage
Garbage: objects: 36651->36645; refs: 417402
Game class is 'xDeathMatch'
Fixing up DM-Antalus
Bringing Level DM-Antalus.myLevel up for play (35) appSeconds: 2.044885...
GameInfo::InitGame : bEnableStatLogging False
UdpServerQuery(crt): Port 7787 successfully bound.
Resolving master0.gamespy.com...
MasterServerUplink: MasterServerGameStats not found - stats uploading disabled.
Defaulting to false
Defaulting to false
Resolving utmaster.openspy.net...
Loading Available Maps
Loading Game Types
xWebAdmin.UTServerAdmin Initialized on port 8080
MasterServerUplink: Resolved utmaster.openspy.net as 157.245.212.59.
AInternetLink Resolve failed: Can't find host master0.gamespy.com (HOST_NOT_FOUND)
UdpGameSpyUplink: Failed to resolve master server address, aborting.
MasterServerUplink: Connection to utmaster.openspy.net established.
Approval APPROVED
Master server assigned our MatchID: 1234
```

Do you have any idea what I could be missing here..?

Thanks a lot,
Best regards,
Pascal
